const colors = {
  alizarinCrimson: '#DC2828',
  anakiwa: '#ADE2FF',
  anakiwaDataVis: '#8CE6FF',
  apple: '#669933',
  astral: '#37939B',
  athensGray: '#EAEDF0',
  azure: '#336699',
  baliHai: '#80A1B6',
  blueStone: '#005A61',
  brightTurquoise: '#00DEEB',
  catskillWhite: '#F4F7FA',
  cerulean: '#00C0F0',
  conifer: '#A0D250',
  dodgerBlue: '#1FA2FF',
  doveGray: '#6E6E6E',
  dullLavender: '#98AEE7',
  eden: '#12475E',
  emerald: '#32C846',
  fiord: '#3B5263',
  flamingo: '#F15A24',
  funGreen: '#008228',
  gallery: '#EDEDED',
  green: '#2F6300',
  greenApple: '#669933',
  heliotrope: '#967AFF',
  hippieBlue: '#5491B1',
  lavender: '#DC6EE1',
  lime: '#A6E400',
  limedSpruce: '#3B464F',
  lochmara: '#0070B9',
  mediumPurple: '#9F4FDC',
  midnightBlue: '#003366',
  mineShaft: '#333333',
  metallicBlue: '#305F72',
  monaLisa: '#FF9494',
  mustard: '#FFD250',
  nevada: '#646E77',
  pickledBluewood: '#37435C',
  pictonBlue: '#44C8F5',
  prussianBlue: '#003366',
  pumpkin: '#F15A24',
  red: '#DF0000',
  regentStBlue: '#A2C3E2',
  robinsEggBlue: '#00C8BE',
  rollingStone: '#808285',
  seagull: '#87CBEE',
  silver: '#CCCCCC',
  thunder: '#231F20',
  tundora: '#4C4C4C',
  turquoiseBlue: '#64EBD7',
  verdunGreen: '#2F6300',
  white: '#FFFFFF',
  wildBlueYonder: '#7B8AAD',
  yellowOrange: '#FF9C46',
};

const palette = {
  background: colors.white,
  highlightBackground: colors.gallery,
  text: {
    dark: colors.mineShaft,
    midGray: colors.doveGray,
    midLight: colors.catskillWhite,
    light: colors.white,
  },
  info: colors.brightTurquoise,
  error: colors.pumpkin,
  form: {
    error: colors.red,
    border: colors.silver,
    warning: colors.flamingo,
  },
  primary: {
    light: colors.dodgerBlue,
    normal: colors.lochmara,
    dark: colors.azure,
    veryDark: colors.prussianBlue,
    darkBackground: colors.pickledBluewood,
    disabled: colors.seagull,
    disabledAccent: colors.baliHai,
  },
  outline: colors.astral,
  accent: colors.silver,
  focus: {
    normal: colors.lochmara,
    dark: colors.lochmara,
  },
  money: {
    light: colors.lime,
    normal: colors.greenApple,
    dark: colors.green,
  },
  grey: {
    // This object is deprecated. Reference colors directly. To be removed on the next major version
    G50: colors.catskillWhite,
    G100: colors.gallery,
    G200: colors.gallery,
    G300: colors.gallery,
    G400: colors.silver,
    G500: colors.silver,
    G600: colors.doveGray,
    G700: colors.doveGray,
    G800: colors.rollingStone,
    G900: colors.thunder,
    A100: colors.silver,
    A200: colors.silver,
    A400: colors.mineShaft,
    A700: colors.doveGray,
  },
  visualizations: [
    colors.anakiwa,
    colors.cerulean,
    colors.turquoiseBlue,
    colors.conifer,
    colors.yellowOrange,
    colors.mediumPurple,
    colors.pictonBlue,
    colors.robinsEggBlue,
    colors.emerald,
    colors.mustard,
    colors.lavender,
    colors.heliotrope,
  ],
  dark: {
    form: {
      error: colors.monaLisa,
    },
    background: colors.thunder,
  },
  colors,
};

export default palette;
